/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.Empresa_Controller;
import empresa.Cadastro_Empresa_View;
import java.awt.Dimension;
import view.contasdiversas.Lista_Contas_Diversas_View;
import view.funcionario.Lista_Funcionarios_View;
import view.fornecedor.Lista_Fornecedor_View;
import view.produtos.Lista_Produtos_View;
import view.cliente.Lista_Cliente_View;
import view.caixa.FluxoCaixa_View;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import model.Empresa_Model;
import model.NivelAcesso_Model;
import model.Usuario_Model;
import sobre.Sobre;
import view.caixa.RelatorioCaixaPeriodo;
import view.cliente.ContasReceberPeriodo;
import view.compra.DebitosCompra_View;
import view.compra.Lista_Compras_View;
import view.condicional.Lista_Condicional_View;
import view.condicional.RelatorioCondicionalPeriodoStatus;
import view.contasdiversas.ContasPagarPeriodo;
import view.contasdiversas.ContasPagasPeriodo;
import view.usuario.Autenticacao_View;
import view.venda.Lista_Vendas_View;
import view.venda.RelatorioVendasPeriodo;

/**
 *
 * @author Claudio Xavier
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();

        jmiCaixa.setEnabled(true);
        jmiClientes.setEnabled(true);
        jmiCOmpra.setEnabled(true);
        jmiCondicional.setEnabled(true);
        jmiFornecedores.setEnabled(true);
        jmiFuncionarios.setEnabled(true);
        jmiBoletos.setEnabled(true);
        jmiContasDiversas.setEnabled(true);
        jmiPecas.setEnabled(true);
        jmiVenda.setEnabled(true);

        this.setExtendedState(this.MAXIMIZED_BOTH);
        carregaLogo();
        //jlImagem.setHorizontalAlignment((int) CENTER_ALIGNMENT);
    }

    public Principal(Usuario_Model usr) {
        initComponents();
        jlUser.setText(usr.getUsuario());

        verificaPermissoes(usr.getNivel());
        this.setExtendedState(this.MAXIMIZED_BOTH);
        carregaLogo();
        //jlImagem.setHorizontalAlignment((int) CENTER_ALIGNMENT);
    }

    public void carregaLogo() {
        Empresa_Controller empc = new Empresa_Controller();
        Empresa_Model emp = empc.buscarEmpresa();
        try {
            File file = new File(emp.getImagem());
            BufferedImage img = ImageIO.read(file);
            ImageIcon icon = new ImageIcon(img);
            jlImagem.setIcon(icon);
            Dimension imageSize = new Dimension(icon.getIconWidth(), icon.getIconHeight());
            jlImagem.setPreferredSize(imageSize);
            jlImagem.revalidate();
            jlImagem.repaint();
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void verificaPermissoes(List<NivelAcesso_Model> niveis) {
        for (NivelAcesso_Model nv : niveis) {
            if (nv.getPermissao().equals("Caixa")) {
                jmiCaixa.setEnabled(true);
            }
            if (nv.getPermissao().equals("Clientes")) {
                jmiClientes.setEnabled(true);
            }
            if (nv.getPermissao().equals("Compras")) {
                jmiCOmpra.setEnabled(true);
            }
            if (nv.getPermissao().equals("Condicional")) {
                jmiCondicional.setEnabled(true);
            }
            if (nv.getPermissao().equals("Fornecedor")) {
                jmiFornecedores.setEnabled(true);
            }
            if (nv.getPermissao().equals("Funcionario")) {
                jmiFuncionarios.setEnabled(true);
            }
            if (nv.getPermissao().equals("Pagar")) {
                jmiBoletos.setEnabled(true);
                jmiContasDiversas.setEnabled(true);
            }
            if (nv.getPermissao().equals("Produtos")) {
                jmiPecas.setEnabled(true);
            }
            if (nv.getPermissao().equals("Vendas")) {
                jmiVenda.setEnabled(true);
            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlData = new javax.swing.JLabel();
        jlHora = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jlUser = new javax.swing.JLabel();
        jlImagem = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMCadastros = new javax.swing.JMenu();
        jmiClientes = new javax.swing.JMenuItem();
        jmiFornecedores = new javax.swing.JMenuItem();
        jmiFuncionarios = new javax.swing.JMenuItem();
        jmiPecas = new javax.swing.JMenuItem();
        jmiEmpresa = new javax.swing.JMenuItem();
        jmOrdemServico = new javax.swing.JMenu();
        jmiVenda = new javax.swing.JMenuItem();
        jmiCOmpra = new javax.swing.JMenuItem();
        jmiCaixa = new javax.swing.JMenuItem();
        jmiContasDiversas = new javax.swing.JMenuItem();
        jmiBoletos = new javax.swing.JMenuItem();
        jmiCondicional = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UnicaBoutique - Principal");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jlData.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlData.setText("jLabel2");

        jlHora.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlHora.setText("jLabel1");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Data: ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Hora: ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Usuário:");

        jlUser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jlUser.setText("jLabel4");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlHora)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlData)
                    .addComponent(jlHora)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jlUser))
                .addContainerGap())
        );

        jlImagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlImagem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlImagemMouseClicked(evt);
            }
        });

        jMCadastros.setText("Manutenção");

        jmiClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jmiClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/1483682997_Add-Male-User.png"))); // NOI18N
        jmiClientes.setText("Clientes");
        jmiClientes.setEnabled(false);
        jmiClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiClientesActionPerformed(evt);
            }
        });
        jMCadastros.add(jmiClientes);

        jmiFornecedores.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jmiFornecedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/1483683490_suppliers.png"))); // NOI18N
        jmiFornecedores.setText("Fornecedores");
        jmiFornecedores.setEnabled(false);
        jmiFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFornecedoresActionPerformed(evt);
            }
        });
        jMCadastros.add(jmiFornecedores);

        jmiFuncionarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jmiFuncionarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/1490376754_user-id.png"))); // NOI18N
        jmiFuncionarios.setText("Funcionários");
        jmiFuncionarios.setEnabled(false);
        jmiFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFuncionariosActionPerformed(evt);
            }
        });
        jMCadastros.add(jmiFuncionarios);

        jmiPecas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jmiPecas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/if_barcode_363078 (1).png"))); // NOI18N
        jmiPecas.setText("Produtos");
        jmiPecas.setEnabled(false);
        jmiPecas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPecasActionPerformed(evt);
            }
        });
        jMCadastros.add(jmiPecas);

        jmiEmpresa.setText("Empresa");
        jmiEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiEmpresaActionPerformed(evt);
            }
        });
        jMCadastros.add(jmiEmpresa);

        jMenuBar1.add(jMCadastros);

        jmOrdemServico.setText("Movimentação");

        jmiVenda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jmiVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/1490377490_shoppingcart_add.png"))); // NOI18N
        jmiVenda.setText("Venda");
        jmiVenda.setEnabled(false);
        jmiVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiVendaActionPerformed(evt);
            }
        });
        jmOrdemServico.add(jmiVenda);

        jmiCOmpra.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jmiCOmpra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/if_file-roller_23794.png"))); // NOI18N
        jmiCOmpra.setText("Compras");
        jmiCOmpra.setEnabled(false);
        jmiCOmpra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCOmpraActionPerformed(evt);
            }
        });
        jmOrdemServico.add(jmiCOmpra);

        jmiCaixa.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jmiCaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/if_Finance_saving_1889200.png"))); // NOI18N
        jmiCaixa.setText("Caixa");
        jmiCaixa.setEnabled(false);
        jmiCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCaixaActionPerformed(evt);
            }
        });
        jmOrdemServico.add(jmiCaixa);

        jmiContasDiversas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jmiContasDiversas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/if_14_Payment_1871430.png"))); // NOI18N
        jmiContasDiversas.setText("Contas Diversas");
        jmiContasDiversas.setEnabled(false);
        jmiContasDiversas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiContasDiversasActionPerformed(evt);
            }
        });
        jmOrdemServico.add(jmiContasDiversas);

        jmiBoletos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jmiBoletos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/if_Certificate_877014.png"))); // NOI18N
        jmiBoletos.setText("Boletos de Compra");
        jmiBoletos.setEnabled(false);
        jmiBoletos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiBoletosActionPerformed(evt);
            }
        });
        jmOrdemServico.add(jmiBoletos);

        jmiCondicional.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jmiCondicional.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/if_Checklist_379508.png"))); // NOI18N
        jmiCondicional.setText("Condicional");
        jmiCondicional.setEnabled(false);
        jmiCondicional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCondicionalActionPerformed(evt);
            }
        });
        jmOrdemServico.add(jmiCondicional);

        jMenuBar1.add(jmOrdemServico);

        jMenu5.setText("Relatórios");

        jMenuItem8.setText("Caixa por Período");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem8);

        jMenuItem10.setText("Vendas por Período");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem10);

        jMenuItem11.setText("Contas a Pagar por Período");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem11);

        jMenuItem12.setText("Contas Pagas por Período");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem12);

        jMenuItem13.setText("Contas a Receber por Período");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem13);

        jMenuItem1.setText("Condicionais por Status ");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem1);

        jMenuBar1.add(jMenu5);

        jMenu2.setText("Ajuda");

        jMenuItem14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/1483684060_sign-info.png"))); // NOI18N
        jMenuItem14.setText("Sobre");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem14);

        jMenuItem15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/1483683822_logout.png"))); // NOI18N
        jMenuItem15.setText("Sair");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem15);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jlImagem, javax.swing.GroupLayout.DEFAULT_SIZE, 1134, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlImagem, javax.swing.GroupLayout.DEFAULT_SIZE, 637, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jmiClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiClientesActionPerformed
        Lista_Cliente_View lcv = new Lista_Cliente_View(null, true);
        lcv.setVisible(true);
    }//GEN-LAST:event_jmiClientesActionPerformed

    private void jmiContasDiversasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiContasDiversasActionPerformed
        Lista_Contas_Diversas_View lcd = new Lista_Contas_Diversas_View(null, true);
        lcd.setVisible(true);
    }//GEN-LAST:event_jmiContasDiversasActionPerformed

    private void jmiFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFornecedoresActionPerformed
        Lista_Fornecedor_View lfv = new Lista_Fornecedor_View(null, true);
        lfv.setVisible(true);
    }//GEN-LAST:event_jmiFornecedoresActionPerformed

    private void jmiPecasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPecasActionPerformed
        Lista_Produtos_View lpv = new Lista_Produtos_View(null, true);
        lpv.setVisible(true);
    }//GEN-LAST:event_jmiPecasActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Date dataSis = new Date();
        SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        jlData.setText(df.format(dataSis));

        Timer timer = new Timer(1000, new hora());

        timer.start();
    }//GEN-LAST:event_formWindowOpened

    private void jmiFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFuncionariosActionPerformed
        Lista_Funcionarios_View lfm = new Lista_Funcionarios_View(null, true);
        lfm.setVisible(true);
    }//GEN-LAST:event_jmiFuncionariosActionPerformed

    private void jmiVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiVendaActionPerformed
        Lista_Vendas_View lvv = new Lista_Vendas_View(null, true);
        lvv.setVisible(true);
    }//GEN-LAST:event_jmiVendaActionPerformed

    private void jmiCOmpraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCOmpraActionPerformed
        Lista_Compras_View lc = new Lista_Compras_View(null, true);
        lc.setVisible(true);
    }//GEN-LAST:event_jmiCOmpraActionPerformed

    private void jmiCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCaixaActionPerformed
        FluxoCaixa_View fc = new FluxoCaixa_View(null, true);
        fc.setVisible(true);
    }//GEN-LAST:event_jmiCaixaActionPerformed

    private void jmiBoletosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiBoletosActionPerformed
        DebitosCompra_View dcv = new DebitosCompra_View(null, true);
        dcv.setVisible(true);
    }//GEN-LAST:event_jmiBoletosActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        RelatorioCaixaPeriodo rcp = new RelatorioCaixaPeriodo(null, true);
        rcp.setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        RelatorioVendasPeriodo rvp = new RelatorioVendasPeriodo(null, true);
        rvp.setVisible(true);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        ContasPagarPeriodo cpp = new ContasPagarPeriodo(null, true);
        cpp.setVisible(true);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        ContasPagasPeriodo cpp = new ContasPagasPeriodo(null, true);
        cpp.setVisible(true);
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        ContasReceberPeriodo crp = new ContasReceberPeriodo(null, true);
        crp.setVisible(true);
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        Sobre sobre = new Sobre(null, true);
        sobre.setVisible(true);
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        int confirmacao = JOptionPane.showConfirmDialog(rootPane, "Deseja sair do sistema? ");
        if (confirmacao == JOptionPane.YES_OPTION) {
            Autenticacao_View av = new Autenticacao_View();
            dispose();
            av.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jmiCondicionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCondicionalActionPerformed
        Lista_Condicional_View lcv = new Lista_Condicional_View(null, true);
        lcv.setVisible(true);
    }//GEN-LAST:event_jmiCondicionalActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        RelatorioCondicionalPeriodoStatus rc = new RelatorioCondicionalPeriodoStatus(null, true);
        rc.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jmiEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiEmpresaActionPerformed
        Empresa_Controller ec = new Empresa_Controller();

        Cadastro_Empresa_View cev = new Cadastro_Empresa_View(null, true, ec.buscarEmpresa());
        cev.setVisible(true);
    }//GEN-LAST:event_jmiEmpresaActionPerformed

    private void jlImagemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlImagemMouseClicked


    }//GEN-LAST:event_jlImagemMouseClicked

    class hora implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            Calendar now = Calendar.getInstance();
            jlHora.setText(String.format("%1$tH:%1tM:%1$tS", now));

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMCadastros;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlData;
    private javax.swing.JLabel jlHora;
    private javax.swing.JLabel jlImagem;
    private javax.swing.JLabel jlUser;
    private javax.swing.JMenu jmOrdemServico;
    private javax.swing.JMenuItem jmiBoletos;
    private javax.swing.JMenuItem jmiCOmpra;
    private javax.swing.JMenuItem jmiCaixa;
    private javax.swing.JMenuItem jmiClientes;
    private javax.swing.JMenuItem jmiCondicional;
    private javax.swing.JMenuItem jmiContasDiversas;
    private javax.swing.JMenuItem jmiEmpresa;
    private javax.swing.JMenuItem jmiFornecedores;
    private javax.swing.JMenuItem jmiFuncionarios;
    private javax.swing.JMenuItem jmiPecas;
    private javax.swing.JMenuItem jmiVenda;
    // End of variables declaration//GEN-END:variables
}
